import { useState, useEffect } from "react";

const allClubs = [
  { id:"arsenal", name:"Arsenal FC", league:"Premier League", leagueCode:"PL", badge:"#EF0107", flag:"🏴󠁧󠁢󠁥󠁮󠁧󠁿", city:"Londen, Engeland", stadium:"Emirates Stadium", capacity:"60.704", membershipName:"Red Membership", membershipCost:"£35–£55 / jaar", waitingTime:"Seizoenkaart: 5–10 jaar", ticketChance:20, difficulty:"hard", membershipRequired:true, about:"Arsenal werkt met een ballot-systeem voor gewilde wedstrijden. Red membership geeft toegang tot het ballot. Loyaliteitspunten bepalen je kans bij topwedstrijden zoals de North London Derby.", steps:[{step:1,title:"Red Membership kopen",desc:"Koop een Red membership via arsenal.com voor £35-55/jaar."},{step:2,title:"Loyaliteitspunten opbouwen",desc:"Hoe meer seizoenen je member bent, hoe groter je kans bij gewilde wedstrijden."},{step:3,title:"Aanmelden voor ballot",desc:"Voor topwedstrijden wordt een ballot uitgeschreven. Meld je altijd aan."},{step:4,title:"Betalen binnen 48 uur",desc:"Als je wint heb je 48 uur om te betalen — daarna vervallen de tickets."},{step:5,title:"Tickets downloaden",desc:"Tickets zijn digitaal via de Arsenal app of per e-mail."}], voorwaarden:["Tickets zijn persoonsgebonden","Loyaliteitspunten bepalen prioriteit","Seizoenkaarthouders hebben altijd voorrang","ID vereist bij ingang"], tips:[{icon:"💡",text:"Begin zo vroeg mogelijk — loyaliteitspunten stapelen op over jaren."},{icon:"⚡",text:"De North London Derby (Arsenal – Tottenham) vereist meerdere jaren loyaliteit."},{icon:"📱",text:"Download de Arsenal app — ballots worden soms eerder aangekondigd via de app."},{icon:"🎯",text:"Meld je aan voor ballots van minder populaire wedstrijden om punten op te bouwen."}], officialUrl:"https://www.arsenal.com/tickets", ticketUrl:"https://www.arsenal.com/tickets" },
  { id:"manchester-city", name:"Manchester City", league:"Premier League", leagueCode:"PL", badge:"#6CABDD", flag:"🏴󠁧󠁢󠁥󠁮󠁧󠁿", city:"Manchester, Engeland", stadium:"Etihad Stadium", capacity:"53.400", membershipName:"Official Membership", membershipCost:"£29–£55 / jaar", waitingTime:"Redelijk toegankelijk", ticketChance:35, difficulty:"medium", membershipRequired:true, about:"Manchester City is vergeleken met andere topclubs relatief toegankelijk. Voor reguliere wedstrijden zijn tickets als member vrij goed te krijgen.", steps:[{step:1,title:"Official Membership kopen",desc:"Via mancity.com een membership kopen voor £29-55/jaar."},{step:2,title:"Ticketshop opent voor members",desc:"Members krijgen voorrang 2-3 weken voor de wedstrijd."},{step:3,title:"Selecteer wedstrijd en stoelen",desc:"Log in en selecteer je gewenste wedstrijd en stoelen."},{step:4,title:"Betalen en bevestigen",desc:"Tickets zijn digitaal beschikbaar in de City app."},{step:5,title:"City app downloaden",desc:"Digitale tickets bij ingang via de officiële app."}], voorwaarden:["Maximaal 4 tickets per membership","Tickets zijn op naam","Doorverkoop niet toegestaan","Gezichtsherkenning mogelijk bij ingang"], tips:[{icon:"💡",text:"Voor reguliere wedstrijden zijn tickets als member vrij goed te krijgen."},{icon:"⚡",text:"Champions League thuiswedstrijden zijn moeilijker — begin vroeg."},{icon:"🏟️",text:"Vak 108 en 109 hebben de meest vocale supporters."},{icon:"📅",text:"Ticketverkoop voor members opent doorgaans 3 weken voor de wedstrijd."}], officialUrl:"https://www.mancity.com/tickets", ticketUrl:"https://www.mancity.com/tickets" },
  { id:"liverpool", name:"Liverpool FC", league:"Premier League", leagueCode:"PL", badge:"#C8102E", flag:"🏴󠁧󠁢󠁥󠁮󠁧󠁿", city:"Liverpool, Engeland", stadium:"Anfield", capacity:"61.276", membershipName:"Official Members Club", membershipCost:"£40 / jaar", waitingTime:"Direct — credits sparen duurt 1-3 jaar", ticketChance:18, difficulty:"medium", membershipRequired:true, about:"Liverpool werkt met een uniek creditsysteem. Elke ballot waar je je voor aanmeldt geeft credits — ook als je geen ticket wint. Hoe meer credits, hoe groter je kans bij topwedstrijden.", steps:[{step:1,title:"Member worden",desc:"Koop een Official Members Club membership voor £40/jaar via liverpoolfc.com."},{step:2,title:"Credits sparen",desc:"Elke ballot aanmelding geeft credits, ook zonder gewonnen ticket."},{step:3,title:"Aanmelden voor alle ballots",desc:"Meld je aan voor elke ballot, ook voor wedstrijden die je niet wilt bezoeken."},{step:4,title:"Afwachten ballot uitslag",desc:"Liverpool mailt je als je gewonnen hebt — 48 uur om te betalen."},{step:5,title:"Credits blijven groeien",desc:"Na 2-3 seizoenen zijn je kansen aanzienlijk groter bij topwedstrijden."}], voorwaarden:["Tickets zijn persoonsgebonden","Credits vervallen niet bij verlenging membership","Seizoenkaarthouders hebben altijd voorrang","Maximaal 2 tickets per membership per wedstrijd"], tips:[{icon:"💡",text:"Begin zo vroeg mogelijk — credits stapelen op over jaren en zijn cruciaal."},{icon:"⚡",text:"Meld je aan voor ELKE ballot, ook voor minder gewilde wedstrijden."},{icon:"🎯",text:"Voor Man United, Man City en Champions League zijn veel credits nodig."},{icon:"📱",text:"Download de Liverpool FC app voor vroege ballotaankondigingen."}], officialUrl:"https://www.liverpoolfc.com/tickets/members", ticketUrl:"https://www.liverpoolfc.com/tickets" },
  { id:"chelsea", name:"Chelsea FC", league:"Premier League", leagueCode:"PL", badge:"#034694", flag:"🏴󠁧󠁢󠁥󠁮󠁧󠁿", city:"Londen, Engeland", stadium:"Stamford Bridge", capacity:"40.341", membershipName:"5th Stand Membership", membershipCost:"£25–£45 / jaar", waitingTime:"Relatief toegankelijk", ticketChance:40, difficulty:"medium", membershipRequired:true, about:"Chelsea heeft met Stamford Bridge een van de kleinere Premier League stadions. Voor members zijn tickets bij reguliere wedstrijden redelijk beschikbaar.", steps:[{step:1,title:"5th Stand Membership kopen",desc:"Koop een membership via chelseafc.com voor £25-45/jaar."},{step:2,title:"Ticketprioriteit voor members",desc:"Members krijgen voorrang 2-3 weken voor de wedstrijd."},{step:3,title:"Online tickets kopen",desc:"Log in en koop tickets via de officiële website of app."},{step:4,title:"Digitale tickets",desc:"Alle tickets zijn digitaal via de Chelsea app."},{step:5,title:"ID meenemen",desc:"ID-controle is standaard bij alle wedstrijden."}], voorwaarden:["Tickets zijn persoonsgebonden","Maximaal 2 tickets per membership","Niet overdraagbaar","ID vereist bij ingang"], tips:[{icon:"💡",text:"Stamford Bridge is compact — elk plekje is dicht bij het veld."},{icon:"⚡",text:"London derby's zijn extra schaars — begin vroeg bij ballot aanmeldingen."},{icon:"🏟️",text:"Vak Matthew Harding Upper heeft de beste atmosfeer."},{icon:"📅",text:"Chelsea bouwt een nieuw stadion — meer capaciteit in de toekomst."}], officialUrl:"https://www.chelseafc.com/en/tickets", ticketUrl:"https://www.chelseafc.com/en/tickets" },
  { id:"tottenham", name:"Tottenham Hotspur", league:"Premier League", leagueCode:"PL", badge:"#132257", flag:"🏴󠁧󠁢󠁥󠁮󠁧󠁿", city:"Londen, Engeland", stadium:"Tottenham Hotspur Stadium", capacity:"62.850", membershipName:"Supporter Membership", membershipCost:"£35–£55 / jaar", waitingTime:"Redelijk toegankelijk", ticketChance:45, difficulty:"medium", membershipRequired:true, about:"Het Tottenham Hotspur Stadium is een van de modernste en grootste stadions van Engeland. Door de grote capaciteit zijn tickets voor reguliere wedstrijden relatief goed te krijgen als member.", steps:[{step:1,title:"Supporter Membership kopen",desc:"Via tottenhamhotspur.com een membership voor £35-55/jaar."},{step:2,title:"Loyalty points opbouwen",desc:"Tottenham werkt met loyaliteitspunten voor schaarse wedstrijden."},{step:3,title:"Tickets kopen via members-shop",desc:"Members krijgen voorrang 2-3 weken voor de wedstrijd."},{step:4,title:"Digitale tickets via app",desc:"Alle tickets zijn digitaal via de officiële Spurs app."},{step:5,title:"ID meenemen",desc:"ID-controle is standaard bij alle wedstrijden."}], voorwaarden:["Tickets zijn persoonsgebonden","Maximaal 4 tickets per account","Niet overdraagbaar","Loyaliteitspunten bepalen prioriteit bij topwedstrijden"], tips:[{icon:"💡",text:"Door de grote capaciteit zijn tickets relatief beter beschikbaar dan andere London clubs."},{icon:"⚡",text:"North London Derby (Spurs – Arsenal) vereist veel loyaliteitspunten."},{icon:"🏟️",text:"Het dak houdt het geluid vast — geweldige atmosfeer."},{icon:"🎯",text:"Bezoekersreviews zijn consistent hoog voor faciliteiten en ervaring."}], officialUrl:"https://www.tottenhamhotspur.com/tickets", ticketUrl:"https://www.tottenhamhotspur.com/tickets" },
  { id:"real-madrid", name:"Real Madrid", league:"La Liga", leagueCode:"LL", badge:"#EE3524", flag:"🇪🇸", city:"Madrid, Spanje", stadium:"Santiago Bernabéu", capacity:"81.044", membershipName:"Madridista", membershipCost:"€35 / jaar", waitingTime:"Direct beschikbaar", ticketChance:25, difficulty:"medium", membershipRequired:true, about:"Real Madrid heeft met het Madridista-programma een van de meest toegankelijke membership-systemen. Direct aan te melden en betaalbaar. Maar voor El Clásico is de concurrentie enorm.", steps:[{step:1,title:"Account aanmaken",desc:"Maak een gratis account aan op realmadrid.com."},{step:2,title:"Madridista membership kopen",desc:"Madridista Basic kost €35/jaar en geeft toegang tot de ticketshop voor members."},{step:3,title:"Wachten op ticketverkoop",desc:"Voor El Clásico opent de memberverkoop 6-8 weken voor de wedstrijd."},{step:4,title:"Inloggen op exact openingsmoment",desc:"Wachtrijen kunnen uren duren — log in op de seconde dat de verkoop opent."},{step:5,title:"Maximaal 2 tickets per account",desc:"Elk Madridista-account mag maximaal 2 tickets kopen. Tickets zijn op naam."}], voorwaarden:["Tickets zijn strikt persoonsgebonden","Geldig ID vereist bij ingang","Doorverkoop boven nominale waarde verboden","Account kan geblokkeerd worden bij misbruik"], tips:[{icon:"💡",text:"Familieleden kunnen elk een apart Madridista-account aanmaken voor meer tickets."},{icon:"⚡",text:"El Clásico tickets zijn binnen minuten uitverkocht — wees op de seconde aanwezig."},{icon:"🏟️",text:"Het gerenoveerde Bernabéu is een van de mooiste stadions ter wereld."},{icon:"📅",text:"Houd officiële social media van Real Madrid in de gaten voor exacte verkoopdata."}], officialUrl:"https://www.realmadrid.com/madridismo", ticketUrl:"https://www.realmadrid.com/en/tickets" },
  { id:"barcelona", name:"FC Barcelona", league:"La Liga", leagueCode:"LL", badge:"#A50044", flag:"🇪🇸", city:"Barcelona, Spanje", stadium:"Estadi Olímpic Lluís Companys", capacity:"53.369", membershipName:"Soci (lid)", membershipCost:"€185 / jaar + inschrijfgeld (~€150)", waitingTime:"6 maanden – 2 jaar", ticketChance:72, difficulty:"hard", membershipRequired:true, about:"FC Barcelona heeft een van de meest exclusieve lidmaatschapssystemen in de voetbalwereld. Als soci heb je voorrang bij alle thuiswedstrijden inclusief El Clásico. Wachttijd is lang maar de investering loont.", steps:[{step:1,title:"Account aanmaken",desc:"Maak een gratis account aan op fcbarcelona.com."},{step:2,title:"Aanmelden wachtlijst",desc:"Via je account aanmelden. Er staan tienduizenden mensen op de lijst."},{step:3,title:"Wachten op uitnodiging",desc:"De wachttijd varieert van 6 mnd tot 2 jaar. Je ontvangt automatisch een e-mail."},{step:4,title:"Uitnodiging accepteren en betalen",desc:"Betaal het jaarlijkse lidmaatschap (€185) plus het eenmalige inschrijfgeld."},{step:5,title:"Tickets kopen als soci",desc:"Tot 4 tickets per wedstrijd. Voor El Clásico maximaal 2 per soci-account."}], voorwaarden:["Minimumleeftijd 16 jaar","Tickets strikt persoonsgebonden","Geen doorverkoop toegestaan","Jaarlijks vernieuwen voor eind juni verplicht"], tips:[{icon:"💡",text:"Meld je aan op de wachtlijst ook als je twijfelt — je kunt altijd weigeren."},{icon:"⚡",text:"El Clásico tickets voor socis gaan open 6-8 weken voor de wedstrijd."},{icon:"👨‍👩‍👦",text:"Elk gezinslid kan een apart soci-lidmaatschap hebben voor meer tickets."},{icon:"🗓️",text:"Vernieuw je lidmaatschap voor eind juni om voorrangsrechten te behouden."}], officialUrl:"https://www.fcbarcelona.com/en/club/membership", ticketUrl:"https://www.fcbarcelona.com/en/tickets" },
  { id:"atletico-madrid", name:"Atlético Madrid", league:"La Liga", leagueCode:"LL", badge:"#CB3524", flag:"🇪🇸", city:"Madrid, Spanje", stadium:"Cívitas Metropolitano", capacity:"68.456", membershipName:"Socio / Abonado", membershipCost:"€180–€600 / seizoen", waitingTime:"Directe aanmelding mogelijk", ticketChance:55, difficulty:"medium", membershipRequired:false, about:"Atlético Madrid heeft een groot en modern stadion. Dagtickets zijn beschikbaar voor minder gewilde wedstrijden. De Madrid derby (Atlético – Real) is de uitzondering — tickets zijn dan extreem schaars.", steps:[{step:1,title:"Account aanmaken",desc:"Maak een account aan op atleticodemadrid.com."},{step:2,title:"Dagtickets of abonnement",desc:"Dagtickets voor losse wedstrijden, abonnement voor alle thuiswedstrijden."},{step:3,title:"Tickets kopen via officiële shop",desc:"Log in en koop tickets 2-4 weken voor de wedstrijd."},{step:4,title:"Metropolitano app",desc:"Download de app voor digitale tickets bij ingang."},{step:5,title:"ID meenemen",desc:"Tickets zijn persoonsgebonden — altijd ID meenemen."}], voorwaarden:["Tickets zijn persoonsgebonden","Geen doorverkoop boven nominale waarde","ID vereist bij ingang","Abonnees hebben altijd voorrang"], tips:[{icon:"💡",text:"Het Metropolitano is een van de mooiste moderne stadions van Europa."},{icon:"⚡",text:"De Madrid derby (Atlético – Real Madrid) is de moeilijkste wedstrijd om tickets voor te krijgen."},{icon:"🏟️",text:"Fondo Sur heeft de meest vocale supporters — geweldige sfeer."},{icon:"📅",text:"Dagtickets zijn voor reguliere La Liga wedstrijden goed beschikbaar."}], officialUrl:"https://www.atleticodemadrid.com/entradas", ticketUrl:"https://www.atleticodemadrid.com/entradas" },
  { id:"sevilla", name:"Sevilla FC", league:"La Liga", leagueCode:"LL", badge:"#CF122D", flag:"🇪🇸", city:"Sevilla, Spanje", stadium:"Estadio Ramón Sánchez Pizjuán", capacity:"43.883", membershipName:"Abonado", membershipCost:"€150–€450 / seizoen", waitingTime:"Relatief toegankelijk", ticketChance:65, difficulty:"easy", membershipRequired:false, about:"Sevilla FC is internationaal bekend maar lokaal gericht. Dagtickets zijn relatief goed beschikbaar voor internationale fans. De sfeer in het Sánchez Pizjuán is legendarisch, zeker in de Europa League.", steps:[{step:1,title:"Account aanmaken",desc:"Maak een account aan op sevillafc.es."},{step:2,title:"Dagtickets kopen",desc:"Beschikbaar via de website 2-3 weken voor de wedstrijd."},{step:3,title:"Kies je vak",desc:"Goede online plattegrond beschikbaar — kies vooraf."},{step:4,title:"Betalen en downloaden",desc:"Tickets zijn digitaal beschikbaar na betaling."},{step:5,title:"ID meenemen",desc:"Tickets zijn op naam — altijd ID meenemen."}], voorwaarden:["Tickets persoonsgebonden","Geen doorverkoop toegestaan","ID vereist bij ingang","Abonnementen hebben altijd voorrang"], tips:[{icon:"💡",text:"Sevilla is een van de betere waarden in La Liga — goed voetbal en betaalbare tickets."},{icon:"⚡",text:"Europa League wedstrijden in het Sánchez Pizjuán hebben een ongekende sfeer."},{icon:"🌅",text:"Combineer met een tour door de historische binnenstad van Sevilla."},{icon:"📅",text:"Dagtickets voor reguliere wedstrijden zijn vaak beschikbaar tot op de dag zelf."}], officialUrl:"https://www.sevillafc.es/entradas", ticketUrl:"https://www.sevillafc.es/entradas" },
  { id:"valencia", name:"Valencia CF", league:"La Liga", leagueCode:"LL", badge:"#EE7623", flag:"🇪🇸", city:"Valencia, Spanje", stadium:"Estadio de Mestalla", capacity:"49.430", membershipName:"Abonado", membershipCost:"€120–€400 / seizoen", waitingTime:"Direct beschikbaar", ticketChance:70, difficulty:"easy", membershipRequired:false, about:"Valencia CF en het iconische Mestalla zijn toegankelijk voor internationale fans. Dagtickets zijn goed beschikbaar. Het Mestalla is een van de oudste en meest karakteristieke stadions van Spanje.", steps:[{step:1,title:"Account aanmaken",desc:"Registreer je op valenciacf.com."},{step:2,title:"Dagtickets kopen",desc:"Beschikbaar via de website of aan de kassa op wedstrijddag."},{step:3,title:"Kies je plek",desc:"Goede online plattegrond beschikbaar — kies vooraf je plek."},{step:4,title:"Digitale tickets",desc:"Na betaling direct beschikbaar als digitaal ticket."},{step:5,title:"ID meenemen",desc:"Altijd ID meenemen voor controle bij ingang."}], voorwaarden:["Tickets op naam","Geen doorverkoop toegestaan","ID vereist bij ingang","Abonnementen hebben voorrang"], tips:[{icon:"💡",text:"Het Mestalla is compact en steil — elk plekje voelt dicht bij het veld."},{icon:"🌅",text:"Valencia combineert geweldig met een stadbezoek — zon, eten en cultuur."},{icon:"💰",text:"Een van de betaalbaardere La Liga ervaringen voor internationale fans."},{icon:"🏟️",text:"Thuiswedstrijden zijn sfervol — Valencia-fans staan bekend om hun passie."}], officialUrl:"https://www.valenciacf.com/entradas", ticketUrl:"https://www.valenciacf.com/entradas" },
  { id:"bayern", name:"Bayern München", league:"Bundesliga", leagueCode:"BL", badge:"#DC052D", flag:"🇩🇪", city:"München, Duitsland", stadium:"Allianz Arena", capacity:"75.024", membershipName:"FC Bayern Mitglied", membershipCost:"€60–€80 / jaar", waitingTime:"Lidmaatschap direct — seizoenkaart 3-8 jaar", ticketChance:30, difficulty:"hard", membershipRequired:true, about:"FC Bayern heeft meer dan 300.000 leden — het meest van elke voetbalclub ter wereld. Een lidmaatschap is betaalbaar maar geeft geen garantie op tickets bij topwedstrijden zoals Der Klassiker.", steps:[{step:1,title:"Lid worden",desc:"Word lid via fcbayern.com voor €60-80/jaar. Direct toegang tot de ledenverkoop."},{step:2,title:"Tickets kopen als lid",desc:"Leden krijgen voorrang bij ticketverkoop 2-3 weken voor de wedstrijd."},{step:3,title:"Wachtrij bij topwedstrijden",desc:"Bij Dortmund en Champions League kan de wachtrij enorm lang zijn."},{step:4,title:"FC Bayern app",desc:"Download de app voor digitale tickets bij ingang."},{step:5,title:"ID meenemen",desc:"Tickets zijn persoonsgebonden — altijd ID meenemen."}], voorwaarden:["Tickets persoonsgebonden","Maximaal 2 tickets per lidmaatschap","Geen doorverkoop","Lange wachttijd voor seizoenkaarten"], tips:[{icon:"💡",text:"Word zo vroeg mogelijk lid — lidmaatschapsjaren tellen mee voor prioriteit."},{icon:"⚡",text:"Der Klassiker (Bayern – Dortmund) vereist jaren lidmaatschap voor goede kans."},{icon:"🏟️",text:"De Allianz Arena verlicht rood bij thuiswedstrijden — een iconisch schouwspel."},{icon:"🎯",text:"Voor reguliere Bundesliga wedstrijden zijn tickets als lid vrij goed te krijgen."}], officialUrl:"https://www.fcbayern.com/mitglied", ticketUrl:"https://www.fcbayern.com/tickets" },
  { id:"dortmund", name:"Borussia Dortmund", league:"Bundesliga", leagueCode:"BL", badge:"#FDE100", flag:"🇩🇪", city:"Dortmund, Duitsland", stadium:"Signal Iduna Park", capacity:"81.365", membershipName:"BVB Mitgliedschaft", membershipCost:"€62–€84 / jaar", waitingTime:"Direct — Gelbe Wand seizoenkaart uitverkocht", ticketChance:35, difficulty:"medium", membershipRequired:true, about:"Signal Iduna Park is het grootste stadion van Duitsland. De Gelbe Wand (Gele Muur) met 25.000 staanplaatsen is een legendarische bucket list ervaring. Een lidmaatschap is betaalbaar.", steps:[{step:1,title:"Lid worden",desc:"Word lid via bvb.de voor €62-84/jaar."},{step:2,title:"Tickets kopen als lid",desc:"Ledenverkoop opent 2-3 weken voor de wedstrijd — wees er vroeg bij."},{step:3,title:"Gelbe Wand tickets",desc:"Staanplaatsen zijn het populairst en snelst uitverkocht bij elk lid."},{step:4,title:"BVB app",desc:"Download de app voor digitale tickets en wedstrijdinformatie."},{step:5,title:"ID meenemen",desc:"Persoonsgebonden tickets — altijd ID meenemen."}], voorwaarden:["Tickets persoonsgebonden","Staanplaatsen alleen voor EU-inwoners","Geen doorverkoop boven nominale prijs","Gelbe Wand is snel uitverkocht"], tips:[{icon:"💡",text:"De sfeer bij de Gelbe Wand in Signal Iduna Park is legendarisch — een absolute bucket list ervaring."},{icon:"⚡",text:"Der Klassiker (BVB – Bayern) is de moeilijkste wedstrijd — begin direct bij opening ledenverkoop."},{icon:"🟡",text:"Staanplaatsen bij de Gelbe Wand zijn goedkoper én hebben de beste sfeer."},{icon:"🏟️",text:"Kom op tijd — de Gelbe Wand staat altijd vol en entree kan lang duren."}], officialUrl:"https://www.bvb.de/Fans/Mitgliedschaft", ticketUrl:"https://www.bvb.de/Tickets" },
  { id:"leverkusen", name:"Bayer 04 Leverkusen", league:"Bundesliga", leagueCode:"BL", badge:"#E32221", flag:"🇩🇪", city:"Leverkusen, Duitsland", stadium:"BayArena", capacity:"30.210", membershipName:"Mitgliedschaft", membershipCost:"€48–€72 / jaar", waitingTime:"Relatief toegankelijk", ticketChance:60, difficulty:"medium", membershipRequired:false, about:"Bayer Leverkusen heeft een compact stadion en is na het eerste kampioenschap in 2024 populairder geworden. Dagtickets zijn nog relatief goed beschikbaar voor internationale fans.", steps:[{step:1,title:"Account aanmaken",desc:"Maak een account aan op bayer04.de voor toegang tot de ticketshop."},{step:2,title:"Dagtickets kopen",desc:"Beschikbaar via de website 2-3 weken voor de wedstrijd."},{step:3,title:"Kies je plek",desc:"Compact stadion — elk plekje is dicht bij het veld."},{step:4,title:"Digitale tickets",desc:"Na betaling direct beschikbaar als digitaal ticket."},{step:5,title:"ID meenemen",desc:"Altijd ID meenemen voor controle bij ingang."}], voorwaarden:["Tickets op naam","Geen doorverkoop boven nominale prijs","ID vereist bij ingang","Leden hebben voorrang"], tips:[{icon:"💡",text:"De BayArena is compact en intiem — geweldige sfeer bij Champions League avonden."},{icon:"⚡",text:"Na het eerste kampioenschap in 2024 zijn tickets populairder geworden — wees er vroeg bij."},{icon:"🏟️",text:"Makkelijk bereikbaar vanuit Keulen (20 min met de trein)."},{icon:"💰",text:"Vergeleken met Bayern en Dortmund zijn tickets hier aanzienlijk betaalbaarder."}], officialUrl:"https://www.bayer04.de/tickets", ticketUrl:"https://www.bayer04.de/tickets" },
  { id:"rb-leipzig", name:"RB Leipzig", league:"Bundesliga", leagueCode:"BL", badge:"#DD0000", flag:"🇩🇪", city:"Leipzig, Duitsland", stadium:"Red Bull Arena", capacity:"47.069", membershipName:"Mitgliedschaft", membershipCost:"€50–€80 / jaar", waitingTime:"Goed beschikbaar", ticketChance:70, difficulty:"easy", membershipRequired:false, about:"RB Leipzig is een jonge club (opgericht 2009) maar speelt al jaren Champions League. Tickets zijn relatief goed beschikbaar — een uitstekende keuze voor internationale fans.", steps:[{step:1,title:"Account aanmaken",desc:"Registreer je op rbleipzig.de voor toegang tot de ticketshop."},{step:2,title:"Dagtickets kopen",desc:"Beschikbaar via de website, vaak tot kort voor de wedstrijd zelf."},{step:3,title:"Kies je plek",desc:"Modern stadion met goede faciliteiten en zichtlijnen."},{step:4,title:"Digitale tickets",desc:"Na betaling direct beschikbaar als digitaal ticket."},{step:5,title:"ID meenemen",desc:"Altijd ID meenemen voor controle bij ingang."}], voorwaarden:["Tickets op naam","Geen doorverkoop boven nominale prijs","ID vereist bij ingang"], tips:[{icon:"💡",text:"Een van de best bereikbare topclubs voor internationale fans — tickets zijn relatief goed beschikbaar."},{icon:"🏟️",text:"De Red Bull Arena is modern en comfortabel met goede faciliteiten."},{icon:"🌍",text:"Leipzig is een bruisende stad met rijke geschiedenis en cultuur."},{icon:"💰",text:"Lagere ticketprijzen dan bij Bayern of Dortmund — goede prijs-kwaliteitverhouding."}], officialUrl:"https://www.rbleipzig.com/tickets", ticketUrl:"https://www.rbleipzig.com/tickets" },
  { id:"frankfurt", name:"Eintracht Frankfurt", league:"Bundesliga", leagueCode:"BL", badge:"#E32219", flag:"🇩🇪", city:"Frankfurt, Duitsland", stadium:"Deutsche Bank Park", capacity:"58.000", membershipName:"Mitgliedschaft", membershipCost:"€48–€72 / jaar", waitingTime:"Redelijk toegankelijk", ticketChance:55, difficulty:"medium", membershipRequired:false, about:"Eintracht Frankfurt heeft een fanatieke aanhang en is na de Europa League winst in 2022 internationaal beroemd. Tickets zijn voor reguliere wedstrijden nog relatief goed te krijgen.", steps:[{step:1,title:"Account aanmaken",desc:"Registreer je op eintracht.de voor toegang tot de ticketshop."},{step:2,title:"Dagtickets of membership",desc:"Dagtickets zijn beschikbaar voor de meeste wedstrijden. Membership geeft voorrang."},{step:3,title:"Tickets kopen",desc:"Online beschikbaar 2-3 weken voor de wedstrijd."},{step:4,title:"Eintracht app",desc:"Digitale tickets via de officiële Eintracht Frankfurt app."},{step:5,title:"ID meenemen",desc:"Altijd ID meenemen voor controle bij ingang."}], voorwaarden:["Tickets op naam","Geen doorverkoop boven nominale prijs","ID vereist bij ingang","Leden hebben voorrang bij schaarse wedstrijden"], tips:[{icon:"💡",text:"De sfeer bij Eintracht Frankfurt is een van de luidste en meest authentieke van de Bundesliga."},{icon:"⚡",text:"Derbywedstrijden zijn schaars in aanbod — begin vroeg met aanmelden."},{icon:"🏆",text:"De Europa League winst in 2022 maakte Eintracht internationaal beroemd."},{icon:"🌍",text:"Frankfurt is via het internationale vliegveld uitstekend bereikbaar."}], officialUrl:"https://www.eintracht.de/tickets", ticketUrl:"https://www.eintracht.de/tickets" },
  { id:"inter-milan", name:"Inter Milan", league:"Serie A", leagueCode:"SA", badge:"#010E80", flag:"🇮🇹", city:"Milaan, Italië", stadium:"San Siro (Giuseppe Meazza)", capacity:"75.923", membershipName:"Inter Club / Abbonamento", membershipCost:"€100–€800 / seizoen", waitingTime:"Seizoenkaart bij beschikbaarheid", ticketChance:50, difficulty:"medium", membershipRequired:false, about:"Inter deelt het iconische San Siro met AC Milan. Dagtickets zijn beschikbaar voor de meeste wedstrijden. De Derby della Madonnina is de uitzondering — een van de grootste derbies ter wereld.", steps:[{step:1,title:"Account aanmaken",desc:"Registreer je op inter.it voor toegang tot de ticketshop."},{step:2,title:"Dagtickets kopen",desc:"Beschikbaar via de website 2-4 weken voor de wedstrijd."},{step:3,title:"Derby della Madonnina",desc:"Voor Inter – AC Milan zijn tickets veel schaarser — begin vroeg."},{step:4,title:"Inter app",desc:"Tickets zijn digitaal beschikbaar via de officiële Inter app."},{step:5,title:"ID meenemen",desc:"Tickets zijn persoonsgebonden — ID altijd meenemen."}], voorwaarden:["Tickets zijn persoonsgebonden","Geen doorverkoop boven nominale waarde","ID vereist bij ingang","Abbonati (seizoenkaarthouders) hebben voorrang"], tips:[{icon:"💡",text:"San Siro is een van de meest iconische stadions ter wereld — een absolute bucket list."},{icon:"⚡",text:"De Derby della Madonnina is een van de grootste derbies ter wereld — tickets extreem schaars."},{icon:"🏟️",text:"Kom op tijd — het stadion is groot en de sfeer begint al buiten."},{icon:"🍕",text:"Milaan biedt naast voetbal mode, gastronomie en cultuur op topniveau."}], officialUrl:"https://www.inter.it/abbonamenti", ticketUrl:"https://www.inter.it/biglietti" },
  { id:"ac-milan", name:"AC Milan", league:"Serie A", leagueCode:"SA", badge:"#FB090B", flag:"🇮🇹", city:"Milaan, Italië", stadium:"San Siro (Giuseppe Meazza)", capacity:"75.923", membershipName:"Milan Club / Abbonamento", membershipCost:"€120–€900 / seizoen", waitingTime:"Seizoenkaart bij beschikbaarheid", ticketChance:48, difficulty:"medium", membershipRequired:false, about:"AC Milan deelt San Siro met Inter. Na jaren wederopbouw is Milan weer een absolute topclub in Europa. Dagtickets zijn beschikbaar voor de meeste wedstrijden via de officiële website.", steps:[{step:1,title:"Account aanmaken",desc:"Registreer je op acmilan.com voor toegang tot de ticketshop."},{step:2,title:"Dagtickets kopen",desc:"Beschikbaar via de website 2-4 weken voor de wedstrijd."},{step:3,title:"Derby della Madonnina",desc:"Voor AC Milan – Inter zijn tickets schaars — begin zo vroeg mogelijk."},{step:4,title:"AC Milan app",desc:"Tickets digitaal beschikbaar via de officiële AC Milan app."},{step:5,title:"ID meenemen",desc:"Persoonsgebonden tickets — ID altijd meenemen."}], voorwaarden:["Tickets zijn persoonsgebonden","Geen doorverkoop boven nominale waarde","ID vereist bij ingang","Abbonati hebben altijd voorrang"], tips:[{icon:"💡",text:"Curva Sud heeft de meest fanatieke AC Milan supporters — beste sfeer."},{icon:"⚡",text:"Champions League avonden in San Siro onder kunstlicht zijn onvergetelijk."},{icon:"🏆",text:"AC Milan is met 7 Champions League titels de meest succesvolle Italiaanse club in Europa."},{icon:"🍕",text:"Milaan combineert topvoetbal met mode, kunst en wereldklasse gastronomie."}], officialUrl:"https://www.acmilan.com/abbonamenti", ticketUrl:"https://www.acmilan.com/biglietti" },
  { id:"juventus", name:"Juventus", league:"Serie A", leagueCode:"SA", badge:"#000000", flag:"🇮🇹", city:"Turijn, Italië", stadium:"Allianz Stadium", capacity:"41.507", membershipName:"Juventus Membership / Abbonamento", membershipCost:"€89–€600 / seizoen", waitingTime:"Membership direct", ticketChance:55, difficulty:"medium", membershipRequired:true, about:"Juventus heeft een eigen modern stadion — het eerste clubeigen stadion van een Italiaanse topclub. Een membership geeft voorrang bij de ticketverkoop voor alle thuiswedstrijden.", steps:[{step:1,title:"Membership kopen",desc:"Koop een membership voor €89/jaar via juventus.com voor ticketprioriteit."},{step:2,title:"Tickets kopen als member",desc:"Members krijgen voorrang 2-3 weken voor de wedstrijd."},{step:3,title:"Juventus app",desc:"Digitale tickets beschikbaar via de officiële Juventus app."},{step:4,title:"ID meenemen",desc:"Persoonsgebonden tickets — altijd ID meenemen."},{step:5,title:"Museum en rondleiding",desc:"Juventus Museum en stadionrondleiding zijn sterk aanbevolen als extra."}], voorwaarden:["Membership geeft voorrang — geen garantie","Tickets persoonsgebonden","Geen doorverkoop boven nominale prijs","ID vereist bij ingang"], tips:[{icon:"💡",text:"Het Allianz Stadium is modern, comfortabel en goed bereikbaar in Turijn."},{icon:"🏆",text:"Juventus is de recordkampioen van Italië met 36 Scudetti."},{icon:"🌍",text:"Turijn is een onderschatte citytrip met rijke cultuur en uitstekende gastronomie."},{icon:"💰",text:"Vergeleken met andere Europese topclubs zijn Juventus tickets relatief betaalbaar."}], officialUrl:"https://www.juventus.com/membership", ticketUrl:"https://www.juventus.com/biglietti" },
  { id:"as-roma", name:"AS Roma", league:"Serie A", leagueCode:"SA", badge:"#830000", flag:"🇮🇹", city:"Rome, Italië", stadium:"Stadio Olimpico", capacity:"70.634", membershipName:"Abbonamento / Tessera del Tifoso", membershipCost:"€120–€500 / seizoen", waitingTime:"Dagtickets goed beschikbaar", ticketChance:62, difficulty:"easy", membershipRequired:false, about:"AS Roma speelt in het indrukwekkende Stadio Olimpico. Dagtickets zijn relatief goed beschikbaar voor internationale fans. Rome als stad maakt een stadionbezoek extra bijzonder.", steps:[{step:1,title:"Account aanmaken",desc:"Registreer je op asroma.com voor toegang tot de ticketshop."},{step:2,title:"Dagtickets kopen",desc:"Beschikbaar via de website 2-4 weken van tevoren."},{step:3,title:"Derby della Capitale",desc:"Roma – Lazio is een van de intensste derbies van Italië — tickets zijn schaars."},{step:4,title:"Digitale tickets",desc:"Via de AS Roma app of als PDF te downloaden na betaling."},{step:5,title:"Tessera del Tifoso of ID",desc:"Een officiële fankaart of ID is vereist bij de ingang."}], voorwaarden:["Tessera del Tifoso of ID vereist bij ingang","Tickets persoonsgebonden","Geen doorverkoop boven nominale prijs","Abbonati hebben altijd voorrang"], tips:[{icon:"💡",text:"Rome is de perfecte voetbaltrip — Colosseum, pasta en een wedstrijd in het Olimpico."},{icon:"⚡",text:"De Derby della Capitale (Roma – Lazio) heeft een van de elektrischste sferen van Europa."},{icon:"🏛️",text:"Het Olimpico werd gebouwd voor de Olympische Spelen van 1960 — historische locatie."},{icon:"🎭",text:"Roma-fans staan wereldwijd bekend om hun creativiteit met tifo's en sfeer."}], officialUrl:"https://www.asroma.com/abbonamenti", ticketUrl:"https://www.asroma.com/biglietti" },
  { id:"napoli", name:"SSC Napoli", league:"Serie A", leagueCode:"SA", badge:"#003DA5", flag:"🇮🇹", city:"Napels, Italië", stadium:"Stadio Diego Armando Maradona", capacity:"54.726", membershipName:"Abbonamento", membershipCost:"€100–€600 / seizoen", waitingTime:"Dagtickets beschikbaar", ticketChance:58, difficulty:"medium", membershipRequired:false, about:"SSC Napoli speelt in het stadion vernoemd naar de legendarische Diego Maradona. Na het eerste kampioenschap in 33 jaar (2023) is de club populairder dan ooit. Een unieke culturele ervaring.", steps:[{step:1,title:"Account aanmaken",desc:"Registreer je op sscnapoli.it voor toegang tot de ticketshop."},{step:2,title:"Dagtickets kopen",desc:"Beschikbaar via de website of aan de kassa voor de wedstrijd."},{step:3,title:"Kies je vak",desc:"Curva B (achter het doel) heeft de meest fanatieke fans en beste sfeer."},{step:4,title:"Digitale tickets",desc:"Via de officïele Napoli app of als PDF te downloaden na betaling."},{step:5,title:"ID meenemen",desc:"Tickets zijn persoonsgebonden — altijd ID meenemen."}], voorwaarden:["Tickets persoonsgebonden","ID vereist bij ingang","Geen doorverkoop boven nominale prijs","Abbonati hebben voorrang"], tips:[{icon:"💡",text:"Het Maradona-stadion heeft een ongekende sfeer — de energie is uniek in heel Europa."},{icon:"🏆",text:"Na het kampioenschap in 2023 zijn Napoli-wedstrijden populairder en schaarser geworden."},{icon:"🍕",text:"Napels is de geboorteplaats van de pizza — een culinaire verkenning is een must."},{icon:"🇦🇷",text:"Maradona wordt in Napels behandeld als een god — zijn erfenis is overal zichtbaar in de stad."}], officialUrl:"https://www.sscnapoli.it/abbonamenti", ticketUrl:"https://www.sscnapoli.it/biglietti" },
  { id:"ajax", name:"Ajax", league:"Eredivisie", leagueCode:"ED", badge:"#CC0000", flag:"🇳🇱", city:"Amsterdam, Nederland", stadium:"Johan Cruijff Arena", capacity:"54.990", membershipName:"Seizoenkaart", membershipCost:"€299–€800 / seizoen", waitingTime:"1–4 jaar wachttijd", ticketChance:85, difficulty:"hard", membershipRequired:true, about:"Ajax heeft meer dan 60.000 mensen op de wachtlijst voor een seizoenkaart. De Johan Cruijff Arena is bij vrijwel elke thuiswedstrijd uitverkocht. Voor De Klassieker is een seizoenkaart nagenoeg vereist.", steps:[{step:1,title:"Aanmelden wachtlijst",desc:"Meld je zo snel mogelijk aan via ajax.nl — meer dan 60.000 mensen staan al te wachten."},{step:2,title:"Wachten (gemiddeld 2-4 jaar)",desc:"De wachttijd hangt af van je gewenste vak. Duurdere vakken hebben doorgaans kortere wachttijden."},{step:3,title:"Uitnodiging en betaling",desc:"Je ontvangt een e-mail zodra er een plek vrijkomt. Je kiest je vak en betaalt het seizoensbedrag."},{step:4,title:"Toegang tot alle thuiswedstrijden",desc:"Je seizoenkaart geeft toegang tot alle thuiswedstrijden, inclusief De Klassieker en Europese duels."},{step:5,title:"Dagtickets als alternatief",desc:"Voor minder gewilde wedstrijden zijn dagtickets beschikbaar via ajax.nl."}], voorwaarden:["Seizoenkaart is persoonsgebonden","Bij 3x niet-gebruik kan kaart worden ingetrokken","Officieel overdragen kan alleen via het Ajax-systeem","Doorverkoop verboden en wordt actief gecontroleerd"], tips:[{icon:"💡",text:"Meld je zo snel mogelijk aan op de wachtlijst — elke dag telt en de lijst groeit elk jaar."},{icon:"⚡",text:"De Klassieker (Ajax – Feyenoord) is nagenoeg onmogelijk zonder seizoenkaart."},{icon:"🏟️",text:"De Johan Cruijff Arena is een van de beste multifunctionele arena's van Europa."},{icon:"🌷",text:"Amsterdam biedt naast Ajax een geweldige citytrip — combineer met een weekend weg."}], officialUrl:"https://www.ajax.nl/tickets/seizoenkaart", ticketUrl:"https://www.ajax.nl/tickets" },
  { id:"feyenoord", name:"Feyenoord", league:"Eredivisie", leagueCode:"ED", badge:"#CC0000", flag:"🇳🇱", city:"Rotterdam, Nederland", stadium:"Stadion Feijenoord (De Kuip)", capacity:"47.500", membershipName:"Seizoenkaart", membershipCost:"€275–€650 / seizoen", waitingTime:"1–5 jaar wachttijd", ticketChance:80, difficulty:"hard", membershipRequired:true, about:"Feyenoord heeft een van de trouwste aanhangen in Nederland. De Kuip zit bij vrijwel elke thuiswedstrijd vol. Voor De Klassieker tegen Ajax is een seizoenkaart nagenoeg vereist.", steps:[{step:1,title:"Account aanmaken",desc:"Maak een Mijn Feyenoord-account aan op feyenoord.nl — verplicht voor tickets en wachtlijst."},{step:2,title:"Aanmelden wachtlijst seizoenkaart",desc:"Via je account aanmelden voor de wachtlijst. Geef aan in welk vak je wilt zitten."},{step:3,title:"Dagtickets als alternatief",desc:"Voor reguliere wedstrijden zijn dagtickets beschikbaar 3-6 weken van tevoren."},{step:4,title:"Wachten op uitnodiging",desc:"De wachttijd is 1-5 jaar afhankelijk van het gewenste vak in het stadion."},{step:5,title:"Seizoenkaart activeren",desc:"Na uitnodiging betaal je het seizoensbedrag en ontvang je je kaart per post of digitaal."}], voorwaarden:["Seizoenkaart is strikt persoonsgebonden","Bij 3x niet-gebruik zonder afmelding kan kaart worden ingetrokken","Doorverkoop verboden en actief gecontroleerd bij alle wedstrijden","Extra ID-controle bij De Klassieker bij alle ingangen"], tips:[{icon:"💡",text:"Meld je zo snel mogelijk aan op de wachtlijst — de lijst groeit elk seizoen flink."},{icon:"⚡",text:"De Klassieker (Feyenoord – Ajax) is nagenoeg onmogelijk te bemachtigen zonder seizoenkaart."},{icon:"🏟️",text:"De Kuip is een van de mooiste en meest karakteristieke stadions van heel Europa."},{icon:"📧",text:"Houd je e-mail goed in de gaten rondom verkoopdata — Feyenoord stuurt geen herinneringen."}], officialUrl:"https://www.feyenoord.nl/club/seizoenkaart", ticketUrl:"https://www.feyenoord.nl/tickets" },
  { id:"psv", name:"PSV Eindhoven", league:"Eredivisie", leagueCode:"ED", badge:"#E8323C", flag:"🇳🇱", city:"Eindhoven, Nederland", stadium:"Philips Stadion", capacity:"35.000", membershipName:"Seizoenkaart", membershipCost:"€199–€550 / seizoen", waitingTime:"1–3 jaar wachttijd", ticketChance:75, difficulty:"medium", membershipRequired:false, about:"PSV is na Ajax de meest succesvolle Nederlandse club. Het Philips Stadion heeft een geweldige sfeer. Dagtickets zijn voor reguliere Eredivisie wedstrijden beschikbaar via de officiële website.", steps:[{step:1,title:"Account aanmaken",desc:"Registreer je op psv.nl voor toegang tot de ticketshop."},{step:2,title:"Dagtickets kopen",desc:"Beschikbaar via de website voor reguliere Eredivisie wedstrijden."},{step:3,title:"Seizoenkaart aanvragen",desc:"Via psv.nl aanmelden voor de wachtlijst voor een seizoenkaart."},{step:4,title:"PSV app",desc:"Digitale tickets beschikbaar via de officiële PSV app bij ingang."},{step:5,title:"ID meenemen",desc:"Tickets zijn persoonsgebonden — altijd ID meenemen."}], voorwaarden:["Tickets persoonsgebonden","Geen doorverkoop boven nominale prijs","ID vereist bij ingang","Seizoenkaarthouders hebben altijd voorrang"], tips:[{icon:"💡",text:"Voor reguliere Eredivisie wedstrijden zijn dagtickets bij PSV redelijk goed te krijgen."},{icon:"⚡",text:"PSV – Ajax is de topwedstrijd van het seizoen — seizoenkaart of vroeg aanmelden vereist."},{icon:"💡",text:"Eindhoven is een design- en technologiestad — bezoek ook het Dutch Design Museum."},{icon:"🏆",text:"PSV speelt regelmatig Champions League — Europese avonden zijn bijzonder."}], officialUrl:"https://www.psv.nl/psv/club/seizoenkaarten.htm", ticketUrl:"https://www.psv.nl/psv/wedstrijden/tickets.htm" },
  { id:"az", name:"AZ Alkmaar", league:"Eredivisie", leagueCode:"ED", badge:"#CC0000", flag:"🇳🇱", city:"Alkmaar, Nederland", stadium:"AFAS Stadion", capacity:"17.023", membershipName:"Seizoenkaart", membershipCost:"€149–€399 / seizoen", waitingTime:"Relatief toegankelijk", ticketChance:80, difficulty:"easy", membershipRequired:false, about:"AZ Alkmaar heeft een trouwe aanhang en een compact stadion met geweldige sfeer. Tickets zijn voor de meeste wedstrijden goed beschikbaar — een uitstekende keuze voor internationale fans.", steps:[{step:1,title:"Account aanmaken",desc:"Registreer je op az.nl voor toegang tot de ticketshop."},{step:2,title:"Dagtickets kopen",desc:"Beschikbaar via de website voor vrijwel alle thuiswedstrijden."},{step:3,title:"Kies je plek",desc:"Compact stadion — elk plekje is dicht bij het veld voor optimale beleving."},{step:4,title:"Digitale tickets",desc:"Via de officiële AZ app of als PDF beschikbaar na betaling."},{step:5,title:"ID meenemen",desc:"Persoonsgebonden tickets — altijd ID meenemen voor controle."}], voorwaarden:["Tickets persoonsgebonden","Geen doorverkoop boven nominale prijs","ID vereist bij ingang"], tips:[{icon:"💡",text:"Het AFAS Stadion is compact — elke stoel voelt dicht bij het veld."},{icon:"💰",text:"Een betaalbare en toegankelijke Eredivisie voetbalervaring."},{icon:"🌷",text:"Alkmaar is een charmante Noord-Hollandse stad — bezoek ook de beroemde kaasmarkt."},{icon:"🏆",text:"AZ speelt regelmatig Europees voetbal met interessante tegenstanders."}], officialUrl:"https://www.az.nl/club/seizoenkaarten", ticketUrl:"https://www.az.nl/wedstrijden/tickets" },
  { id:"fc-utrecht", name:"FC Utrecht", league:"Eredivisie", leagueCode:"ED", badge:"#CC0000", flag:"🇳🇱", city:"Utrecht, Nederland", stadium:"Stadion Galgenwaard", capacity:"24.000", membershipName:"Seizoenkaart", membershipCost:"€149–€350 / seizoen", waitingTime:"Direct beschikbaar", ticketChance:85, difficulty:"easy", membershipRequired:false, about:"FC Utrecht is een gezellige club met een betrokken aanhang. Galgenwaard heeft een goede sfeer en tickets zijn voor alle thuiswedstrijden goed beschikbaar. Utrecht als stad is een perfecte dagtrip.", steps:[{step:1,title:"Account aanmaken",desc:"Registreer je op fcutrecht.nl voor toegang tot de ticketshop."},{step:2,title:"Dagtickets kopen",desc:"Beschikbaar via de website voor alle thuiswedstrijden."},{step:3,title:"Kies je plek",desc:"Goede online plattegrond beschikbaar — kies vooraf je gewenste plek."},{step:4,title:"Digitale tickets",desc:"Via de officiële FC Utrecht app of als PDF beschikbaar na betaling."},{step:5,title:"ID meenemen",desc:"Persoonsgebonden tickets — altijd ID meenemen voor controle bij ingang."}], voorwaarden:["Tickets persoonsgebonden","Geen doorverkoop boven nominale prijs","ID vereist bij ingang"], tips:[{icon:"💡",text:"FC Utrecht is toegankelijk en betaalbaar — uitstekend voor je eerste Eredivisie-ervaring."},{icon:"🌆",text:"Utrecht is een prachtige stad met grachten, terrassen en rijke cultuur."},{icon:"💰",text:"Een van de betaalbaardere voetbalervaringen in Nederland."},{icon:"🚂",text:"Utrecht Centraal is het drukste treinstation van Nederland — uitstekend bereikbaar."}], officialUrl:"https://www.fcutrecht.nl/seizoenkaarten", ticketUrl:"https://www.fcutrecht.nl/tickets" },
];

const leagueConfig = { "Premier League":{badge:"#E90052"}, "La Liga":{badge:"#EE3524"}, "Bundesliga":{badge:"#d3010c"}, "Serie A":{badge:"#024494"}, "Eredivisie":{badge:"#FF6B00"} };
const difficultyConfig = { easy:{label:"Makkelijk",color:"#00e676"}, medium:{label:"Gemiddeld",color:"#ffd740"}, hard:{label:"Moeilijk",color:"#ff5252"} };
const LEAGUES = ["Alle","Premier League","La Liga","Bundesliga","Serie A","Eredivisie"];
const S = { page:{minHeight:"100vh",background:"#0a0a0a",color:"#fff",fontFamily:"'DM Sans',sans-serif",fontWeight:300}, bebas:{fontFamily:"'Bebas Neue',cursive"}, mono:{fontFamily:"'DM Mono',monospace"}, gold:{color:"#c8a84b"}, card:{background:"linear-gradient(135deg,#111,#181818)",border:"1px solid #222",borderRadius:14,overflow:"hidden"} };

function ChanceBar({ value }) {
  const color = value >= 70 ? "#00e676" : value >= 40 ? "#ffd740" : "#ff5252";
  return (
    <div>
      <div style={{display:"flex",justifyContent:"space-between",marginBottom:4}}>
        <span style={{fontSize:12,color:"#555"}}>Ticketkans topwedstrijden</span>
        <span style={{fontSize:13,color,fontWeight:700,...S.mono}}>{value}%</span>
      </div>
      <div style={{height:5,background:"#1a1a1a",borderRadius:3,overflow:"hidden"}}>
        <div style={{height:"100%",width:`${value}%`,background:`linear-gradient(90deg,${color}44,${color})`,borderRadius:3}} />
      </div>
    </div>
  );
}

function ClubCard({ club, onClick }) {
  const diff = difficultyConfig[club.difficulty];
  const lc = leagueConfig[club.league] || {badge:"#555"};
  return (
    <div onClick={onClick} style={{...S.card,cursor:"pointer",transition:"transform .2s, border-color .2s"}}
      onMouseEnter={e=>{e.currentTarget.style.transform="translateY(-3px)";e.currentTarget.style.borderColor=lc.badge;}}
      onMouseLeave={e=>{e.currentTarget.style.transform="none";e.currentTarget.style.borderColor="#222";}}>
      <div style={{height:3,background:`linear-gradient(90deg,${lc.badge},transparent)`}} />
      <div style={{padding:"18px"}}>
        <div style={{display:"flex",justifyContent:"space-between",alignItems:"flex-start",marginBottom:12}}>
          <div>
            <div style={{fontSize:18,marginBottom:3}}>{club.flag}</div>
            <div style={{...S.bebas,fontSize:18,color:"#fff",letterSpacing:".04em",lineHeight:1.1}}>{club.name}</div>
            <div style={{color:"#444",fontSize:10,marginTop:2,...S.mono}}>{club.league} · {club.stadium}</div>
          </div>
          <div style={{textAlign:"right"}}>
            <div style={{background:diff.color+"1a",border:`1px solid ${diff.color}33`,color:diff.color,fontSize:9,padding:"2px 8px",borderRadius:20,marginBottom:5}}>{diff.label}</div>
            <div style={{color:"#555",fontSize:10,...S.mono}}>{club.membershipCost}</div>
          </div>
        </div>
        <ChanceBar value={club.ticketChance} />
        <div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginTop:10}}>
          <div style={{color:"#333",fontSize:10}}>⏳ {club.waitingTime}</div>
          <span style={{...S.bebas,fontSize:12,color:lc.badge,letterSpacing:".05em"}}>Bekijk gids →</span>
        </div>
      </div>
    </div>
  );
}

function ClubDetail({ club, onClose }) {
  const diff = difficultyConfig[club.difficulty];
  const lc = leagueConfig[club.league] || {badge:"#555"};
  return (
    <div style={{background:"#0a0a0a",minHeight:"100vh"}}>
      <div style={{background:`linear-gradient(135deg,${lc.badge}18,#111)`,borderBottom:"1px solid #1a1a1a",padding:"28px 24px"}}>
        <div style={{maxWidth:860,margin:"0 auto"}}>
          <button onClick={onClose} style={{background:"transparent",border:"1px solid #222",borderRadius:7,padding:"6px 14px",color:"#555",...S.mono,fontSize:11,cursor:"pointer",marginBottom:20}}>← Terug naar overzicht</button>
          <div style={{display:"flex",alignItems:"flex-start",justifyContent:"space-between",flexWrap:"wrap",gap:16}}>
            <div>
              <div style={{fontSize:28,marginBottom:6}}>{club.flag}</div>
              <h1 style={{...S.bebas,fontSize:"clamp(32px,6vw,60px)",color:"#fff",lineHeight:.95,letterSpacing:".03em",marginBottom:6}}>{club.name}</h1>
              <div style={{color:"#444",fontSize:13}}>{club.city} · {club.stadium} · {club.capacity} plaatsen</div>
            </div>
            <div style={{display:"flex",gap:10,flexWrap:"wrap"}}>
              {[["Membership",club.membershipName],["Kosten",club.membershipCost],["Wachttijd",club.waitingTime]].map(([l,v])=>(
                <div key={l} style={{background:"#111",border:"1px solid #1e1e1e",borderRadius:10,padding:"10px 14px",textAlign:"center"}}>
                  <div style={{...S.mono,fontSize:9,color:"#333",marginBottom:3,letterSpacing:".08em"}}>{l.toUpperCase()}</div>
                  <div style={{...S.bebas,fontSize:13,color:"#ccc",letterSpacing:".04em",maxWidth:140}}>{v}</div>
                </div>
              ))}
            </div>
          </div>
        </div>
      </div>
      <div style={{maxWidth:860,margin:"0 auto",padding:"24px"}}>
        <div style={{display:"grid",gridTemplateColumns:"1fr auto",gap:14,marginBottom:20,alignItems:"start"}}>
          <div style={{background:"#111",border:"1px solid #1a1a1a",borderRadius:12,padding:"18px"}}>
            <div style={{...S.mono,fontSize:10,color:"#c8a84b",letterSpacing:".1em",marginBottom:8}}>OVER DIT MEMBERSHIP</div>
            <p style={{fontSize:13,color:"#555",lineHeight:1.8}}>{club.about}</p>
          </div>
          <div style={{background:"#111",border:"1px solid #1a1a1a",borderRadius:12,padding:"18px",minWidth:180}}>
            <div style={{...S.mono,fontSize:10,color:"#c8a84b",letterSpacing:".1em",marginBottom:14}}>SNEL OVERZICHT</div>
            <div style={{marginBottom:14}}>
              <span style={{background:diff.color+"1a",border:`1px solid ${diff.color}33`,color:diff.color,fontSize:12,padding:"4px 12px",borderRadius:20}}>{diff.label}</span>
            </div>
            <div style={{...S.mono,fontSize:10,color:"#333",marginBottom:5}}>MEMBERSHIP VEREIST</div>
            <div style={{fontSize:13,color:club.membershipRequired?"#ff5252":"#00e676",marginBottom:14}}>{club.membershipRequired?"Ja — voor topwedstrijden":"Nee — dagtickets beschikbaar"}</div>
            <ChanceBar value={club.ticketChance} />
          </div>
        </div>
        <div style={{background:"#0d0d0d",border:"1px solid #1a1a1a",borderRadius:14,padding:"22px",marginBottom:14}}>
          <div style={{...S.bebas,fontSize:16,letterSpacing:".08em",color:lc.badge,marginBottom:18}}>📋 STAPPENPLAN</div>
          {club.steps.map((s,i)=>(
            <div key={i} style={{display:"flex",gap:12,marginBottom:14}}>
              <div style={{minWidth:26,height:26,borderRadius:"50%",background:lc.badge,display:"flex",alignItems:"center",justifyContent:"center",...S.bebas,fontSize:13,color:"#fff",flexShrink:0}}>{s.step}</div>
              <div style={{flex:1,paddingBottom:14,borderBottom:i<club.steps.length-1?"1px solid #1a1a1a":"none"}}>
                <div style={{color:"#ddd",fontWeight:500,fontSize:13,marginBottom:4}}>{s.title}</div>
                <div style={{color:"#555",fontSize:12,lineHeight:1.7}}>{s.desc}</div>
              </div>
            </div>
          ))}
        </div>
        <div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:12,marginBottom:18}}>
          <div style={{background:"#0d0d0d",border:"1px solid #1a1a1a",borderRadius:14,padding:"20px"}}>
            <div style={{...S.bebas,fontSize:15,letterSpacing:".08em",color:"#ffd740",marginBottom:14}}>⚠️ VOORWAARDEN</div>
            {club.voorwaarden.map((v,i)=>(
              <div key={i} style={{display:"flex",gap:7,marginBottom:9,alignItems:"flex-start"}}>
                <span style={{color:"#ffd74033",flexShrink:0}}>→</span>
                <span style={{color:"#555",fontSize:12,lineHeight:1.6}}>{v}</span>
              </div>
            ))}
          </div>
          <div style={{background:"#0d0d0d",border:"1px solid #1a2a1a",borderRadius:14,padding:"20px"}}>
            <div style={{...S.bebas,fontSize:15,letterSpacing:".08em",color:"#00e676",marginBottom:14}}>💡 INSIDER TIPS</div>
            {club.tips.map((t,i)=>(
              <div key={i} style={{display:"flex",gap:9,marginBottom:10,alignItems:"flex-start",paddingBottom:10,borderBottom:i<club.tips.length-1?"1px solid #1a1a1a":"none"}}>
                <span style={{fontSize:15,flexShrink:0}}>{t.icon}</span>
                <span style={{color:"#555",fontSize:12,lineHeight:1.6}}>{t.text}</span>
              </div>
            ))}
          </div>
        </div>
        <div style={{display:"flex",gap:10}}>
          <a href={club.officialUrl} target="_blank" rel="noopener noreferrer" style={{display:"inline-block",background:lc.badge,color:"#fff",...S.bebas,fontSize:14,letterSpacing:".08em",padding:"10px 20px",borderRadius:8,textDecoration:"none"}}>Membership aanvragen →</a>
          <a href={club.ticketUrl} target="_blank" rel="noopener noreferrer" style={{display:"inline-block",background:"transparent",border:`1px solid ${lc.badge}`,color:lc.badge,...S.bebas,fontSize:14,letterSpacing:".08em",padding:"10px 20px",borderRadius:8,textDecoration:"none"}}>Tickets bekijken →</a>
        </div>
        <div style={{marginTop:18,background:"#0d0d0d",border:"1px solid #1a1a1a",borderRadius:10,padding:"11px 14px"}}>
          <div style={{color:"#2a2a2a",fontSize:11,lineHeight:1.7}}>
            <strong style={{color:"#333"}}>Disclaimer:</strong> Ticketscouter informeert uitsluitend over officiële ticketkanalen. Alle tickets zijn persoonsgebonden. Doorverkoop boven nominale waarde is bij de meeste clubs verboden.
          </div>
        </div>
      </div>
    </div>
  );
}

function LandingPage({ onEnter }) {
  const [email, setEmail] = useState("");
  const [sent, setSent] = useState(false);
  const [loaded, setLoaded] = useState(false);
  useEffect(() => { setTimeout(() => setLoaded(true), 80); }, []);
  const fd = d => ({opacity:loaded?1:0,transform:loaded?"none":"translateY(18px)",transition:`opacity .55s ${d}s, transform .55s ${d}s`});
  return (
    <div>
      <div style={{minHeight:"88vh",display:"flex",alignItems:"center",padding:"60px 24px 80px",position:"relative",overflow:"hidden"}}>
        <div style={{position:"absolute",inset:0,backgroundImage:"linear-gradient(#181818 1px,transparent 1px),linear-gradient(90deg,#181818 1px,transparent 1px)",backgroundSize:"52px 52px",opacity:.14,maskImage:"radial-gradient(ellipse 80% 70% at 50% 50%,black,transparent)"}} />
        <div style={{position:"absolute",top:"45%",left:"58%",transform:"translate(-50%,-50%)",width:560,height:560,borderRadius:"50%",background:"radial-gradient(circle,rgba(200,168,75,.08) 0%,transparent 70%)",pointerEvents:"none"}} />
        <div style={{maxWidth:860,margin:"0 auto",position:"relative",zIndex:1,width:"100%"}}>
          <div style={{...fd(0.05),display:"inline-flex",alignItems:"center",gap:7,border:"1px solid rgba(200,168,75,.3)",background:"rgba(200,168,75,.07)",borderRadius:20,padding:"5px 13px",...S.mono,fontSize:11,color:"#c8a84b",letterSpacing:".07em",marginBottom:24}}>
            <span style={{width:6,height:6,borderRadius:"50%",background:"#00e676",display:"inline-block",animation:"pulse 2s infinite"}} />
            25 clubs · 5 competities · Eerlijke gidsen
          </div>
          <h1 style={{...S.bebas,fontSize:"clamp(60px,11vw,110px)",lineHeight:.93,letterSpacing:".03em",color:"#fff",marginBottom:14,...fd(0.12)}}>
            Scout your<br />perfect<br /><span style={S.gold}>match ticket.</span>
          </h1>
          <p style={{fontSize:16,color:"#555",lineHeight:1.8,maxWidth:480,marginBottom:36,fontWeight:300,...fd(0.22)}}>
            Ticketscouter legt eerlijk uit hoe je aan tickets komt voor de grootste wedstrijden ter wereld — van El Clásico tot De Klassieker en Der Klassiker.
          </p>
          <div style={fd(0.30)}>
            {!sent ? (
              <div style={{display:"flex",gap:8,maxWidth:420,marginBottom:12}}>
                <input value={email} onChange={e=>setEmail(e.target.value)} onKeyDown={e=>e.key==="Enter"&&email.includes("@")&&setSent(true)} placeholder="jouw@email.nl" style={{flex:1,background:"#111",border:"1px solid #222",borderRadius:8,padding:"13px 15px",color:"#fff",fontFamily:"'DM Sans',sans-serif",fontSize:14,outline:"none"}} />
                <button onClick={()=>email.includes("@")&&setSent(true)} style={{background:"linear-gradient(135deg,#c8a84b,#f0d080)",color:"#000",border:"none",borderRadius:8,padding:"13px 20px",...S.bebas,fontSize:16,letterSpacing:".07em",cursor:"pointer",whiteSpace:"nowrap"}}>Aanmelden →</button>
              </div>
            ) : (
              <div style={{display:"flex",alignItems:"center",gap:8,color:"#00e676",...S.mono,fontSize:13,marginBottom:12}}>✓ Gelukt! Je ontvangt als eerste updates.</div>
            )}
            <div style={{...S.mono,fontSize:10,color:"#2a2a2a"}}>Gratis · Geen creditcard · Altijd opzegbaar</div>
          </div>
        </div>
      </div>
      <div style={{display:"flex",background:"#0d0d0d",borderTop:"1px solid #1a1a1a",borderBottom:"1px solid #1a1a1a"}}>
        {[["25","Clubs uitgewerkt"],["5","Competities"],["100%","Officiële info"],["Gratis","Starten"]].map(([n,l])=>(
          <div key={l} style={{flex:1,padding:"20px 14px",textAlign:"center",borderRight:"1px solid #1a1a1a"}}>
            <div style={{...S.bebas,fontSize:30,color:"#fff",lineHeight:1}}>{n}</div>
            <div style={{...S.mono,fontSize:10,color:"#333",marginTop:4}}>{l}</div>
          </div>
        ))}
      </div>
      <div style={{padding:"80px 24px"}}>
        <div style={{maxWidth:860,margin:"0 auto"}}>
          <div style={{...S.mono,fontSize:10,color:"#c8a84b",letterSpacing:".12em",textTransform:"uppercase",marginBottom:10}}>Coverage</div>
          <h2 style={{...S.bebas,fontSize:"clamp(32px,5vw,52px)",color:"#fff",lineHeight:.97,letterSpacing:".03em",marginBottom:40}}>De grote vijf <span style={S.gold}>volledig gedekt.</span></h2>
          <div style={{display:"grid",gridTemplateColumns:"repeat(5,1fr)",gap:2,background:"#1a1a1a",borderRadius:14,overflow:"hidden"}}>
            {[
              {league:"Premier League",code:"PL",badge:"#E90052",clubs:["Arsenal","Man City","Liverpool","Chelsea","Tottenham"]},
              {league:"La Liga",code:"LL",badge:"#EE3524",clubs:["Real Madrid","FC Barcelona","Atlético","Sevilla","Valencia"]},
              {league:"Bundesliga",code:"BL",badge:"#d3010c",clubs:["Bayern","Dortmund","Leverkusen","RB Leipzig","Frankfurt"]},
              {league:"Serie A",code:"SA",badge:"#024494",clubs:["Inter Milan","AC Milan","Juventus","AS Roma","Napoli"]},
              {league:"Eredivisie",code:"ED",badge:"#FF6B00",clubs:["Ajax","Feyenoord","PSV","AZ Alkmaar","FC Utrecht"]},
            ].map(col=>(
              <div key={col.code} style={{background:"#0a0a0a",padding:"16px 12px"}}>
                <div style={{display:"flex",alignItems:"center",gap:6,marginBottom:10,paddingBottom:8,borderBottom:"1px solid #1a1a1a"}}>
                  <span style={{background:col.badge,color:"#fff",...S.mono,fontSize:9,fontWeight:700,padding:"2px 5px",borderRadius:4}}>{col.code}</span>
                </div>
                {col.clubs.map(n=>(
                  <div key={n} style={{display:"flex",alignItems:"center",gap:5,padding:"5px 0",borderBottom:"1px solid #141414",fontSize:11,color:"#444"}}>
                    <span style={{width:4,height:4,borderRadius:"50%",background:col.badge,flexShrink:0}} />{n}
                  </div>
                ))}
              </div>
            ))}
          </div>
          <div style={{textAlign:"center",marginTop:32}}>
            <button onClick={onEnter} style={{background:"linear-gradient(135deg,#c8a84b,#f0d080)",color:"#000",border:"none",borderRadius:9,padding:"13px 30px",...S.bebas,fontSize:17,letterSpacing:".08em",cursor:"pointer"}}>Bekijk alle club gidsen →</button>
          </div>
        </div>
      </div>
    </div>
  );
}

function ClubsPage() {
  const [filter, setFilter] = useState("Alle");
  const [selectedClub, setSelectedClub] = useState(null);
  const [loaded, setLoaded] = useState(false);
  useEffect(() => { setTimeout(() => setLoaded(true), 80); }, []);
  if (selectedClub) return <ClubDetail club={selectedClub} onClose={()=>setSelectedClub(null)} />;
  const filtered = filter === "Alle" ? allClubs : allClubs.filter(c=>c.league===filter);
  return (
    <div style={{maxWidth:860,margin:"0 auto",padding:"24px"}}>
      <div style={{marginBottom:22}}>
        <div style={{...S.bebas,fontSize:26,letterSpacing:".05em",marginBottom:6}}>Club Gidsen</div>
        <p style={{color:"#444",fontSize:13,lineHeight:1.8,maxWidth:560}}>25 clubs volledig uitgewerkt — stappenplan, kosten, wachttijden, voorwaarden en insider tips.</p>
      </div>
      <div style={{display:"flex",gap:16,marginBottom:16,flexWrap:"wrap"}}>
        {Object.entries(difficultyConfig).map(([k,v])=>(
          <div key={k} style={{display:"flex",alignItems:"center",gap:6}}>
            <span style={{width:7,height:7,borderRadius:"50%",background:v.color,display:"inline-block"}} />
            <span style={{color:"#333",fontSize:11}}>{v.label} te verkrijgen</span>
          </div>
        ))}
      </div>
      <div style={{display:"flex",gap:7,marginBottom:22,flexWrap:"wrap"}}>
        {LEAGUES.map(l=>(
          <button key={l} onClick={()=>setFilter(l)} style={{background:filter===l?"#fff":"transparent",color:filter===l?"#000":"#333",border:filter===l?"none":"1px solid #1a1a1a",...S.bebas,fontSize:12,letterSpacing:".06em",padding:"5px 14px",borderRadius:20,cursor:"pointer",transition:"all .2s"}}>{l}</button>
        ))}
      </div>
      <div style={{display:"grid",gridTemplateColumns:"repeat(auto-fill,minmax(260px,1fr))",gap:12,opacity:loaded?1:0,transform:loaded?"none":"translateY(12px)",transition:"opacity .5s,transform .5s"}}>
        {filtered.map((c,i)=>(
          <div key={c.id} style={{opacity:loaded?1:0,transform:loaded?"none":"translateY(18px)",transition:`opacity .4s ${i*.04}s,transform .4s ${i*.04}s`}}>
            <ClubCard club={c} onClick={()=>setSelectedClub(c)} />
          </div>
        ))}
      </div>
    </div>
  );
}

export default function App() {
  const [view, setView] = useState("landing");
  return (
    <div style={S.page}>
      <style>{`
        @import url('https://fonts.googleapis.com/css2?family=Bebas+Neue&family=DM+Sans:wght@300;400;500&family=DM+Mono:wght@400;500&display=swap');
        * { box-sizing:border-box; margin:0; padding:0; }
        body { overflow-x:hidden; }
        @keyframes pulse { 0%,100%{opacity:1} 50%{opacity:.3} }
      `}</style>
      <div style={{position:"sticky",top:0,zIndex:200,background:"rgba(10,10,10,.96)",backdropFilter:"blur(14px)",borderBottom:"1px solid #1a1a1a"}}>
        <div style={{maxWidth:860,margin:"0 auto",padding:"0 24px",height:52,display:"flex",justifyContent:"space-between",alignItems:"center"}}>
          <button onClick={()=>setView("landing")} style={{background:"none",border:"none",cursor:"pointer",display:"flex",alignItems:"center",gap:9}}>
            <div style={{width:27,height:27,borderRadius:6,background:"linear-gradient(135deg,#c8a84b,#f0d080)",display:"flex",alignItems:"center",justifyContent:"center",fontSize:13}}>⚽</div>
            <span style={{...S.bebas,fontSize:20,letterSpacing:".08em",color:"#fff"}}>TICKETSCOUTER</span>
          </button>
          {view==="landing"
            ? <button onClick={()=>setView("app")} style={{background:"linear-gradient(135deg,#c8a84b,#f0d080)",color:"#000",border:"none",borderRadius:7,padding:"7px 16px",...S.bebas,fontSize:14,letterSpacing:".07em",cursor:"pointer"}}>Bekijk gidsen →</button>
            : <button onClick={()=>setView("landing")} style={{background:"transparent",color:"#333",border:"1px solid #1a1a1a",borderRadius:7,padding:"7px 16px",...S.bebas,fontSize:13,letterSpacing:".07em",cursor:"pointer"}}>← Home</button>
          }
        </div>
      </div>
      {view==="landing" && <LandingPage onEnter={()=>setView("app")} />}
      {view==="app" && <ClubsPage />}
      <div style={{background:"#0a0a0a",borderTop:"1px solid #141414",padding:"20px 24px",display:"flex",justifyContent:"space-between",alignItems:"center"}}>
        <span style={{...S.bebas,fontSize:15,letterSpacing:".07em",color:"#222"}}>⚽ TICKETSCOUTER</span>
        <span style={{...S.mono,fontSize:10,color:"#1a1a1a"}}>© 2026 Ticketscouter.com</span>
        <div style={{display:"flex",gap:16}}>
          {["Privacy","Voorwaarden","Contact"].map(l=><span key={l} style={{...S.mono,fontSize:10,color:"#222",cursor:"pointer"}}>{l}</span>)}
        </div>
      </div>
    </div>
  );
}
